name: Generate Snake Animation (Last 2 Years)

on:
  schedule:
    - cron: "0 */12 * * *"  
  workflow_dispatch:        
  push:
    branches:
      - main                

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write       

    steps:
      - name: Generate Snake SVG (2-year range)
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }} 
          outputs: |
            dist/snake.svg?palette=rainbow&range=last_2_years  # Rango de 2 años
            dist/snake-dark.svg?palette=github-dark&range=last_2_years  # Versión oscura

      - name: Upload Snake to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  
          build_dir: dist        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
